CREATE TABLE weekly_bills (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    week_number INT NOT NULL,
    year INT NOT NULL,
    bill_name VARCHAR(100) NOT NULL,
    bill_description TEXT,
    bill_type VARCHAR(30) NOT NULL,
    version_a JSONB NOT NULL,
    version_b JSONB NOT NULL,
    version_c JSONB NOT NULL,
    special_rules JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT false,
    play_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(week_number, year)
);

CREATE INDEX idx_weekly_bills_active ON weekly_bills(is_active) WHERE is_active = true;
CREATE INDEX idx_weekly_bills_week ON weekly_bills(year, week_number);

-- 預填充 12 週的法案
INSERT INTO weekly_bills (week_number, year, bill_name, bill_description, bill_type, version_a, version_b, version_c, special_rules) VALUES
(1, 2026, '穀物法案', '關於進口穀物的關稅政策', 'economic', 
  '{"name": "自由貿易版", "description": "完全取消穀物進口關稅", "reformist_bonus": 10, "royalist_bonus": -5}'::jsonb,
  '{"name": "保護關稅版", "description": "維持高額進口關稅保護地主", "reformist_bonus": -5, "royalist_bonus": 10}'::jsonb,
  '{"name": "漸進調降版", "description": "五年內逐步調降關稅", "reformist_bonus": 5, "royalist_bonus": 3}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 0}'::jsonb),
(2, 2026, '選舉改革法案', '關於擴大選舉權的提案', 'political',
  '{"name": "普選版", "description": "所有成年男性皆有投票權", "reformist_bonus": 15, "royalist_bonus": -10}'::jsonb,
  '{"name": "維持現狀版", "description": "僅地主有投票權", "reformist_bonus": -10, "royalist_bonus": 15}'::jsonb,
  '{"name": "有限擴大版", "description": "降低財產門檻", "reformist_bonus": 5, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": -5, "alliance_bonus": 0}'::jsonb),
(3, 2026, '工廠法案', '關於工廠勞動條件的規範', 'social',
  '{"name": "十小時工作版", "description": "限制每日工時十小時", "reformist_bonus": 10, "royalist_bonus": -3}'::jsonb,
  '{"name": "自由放任版", "description": "由市場決定勞動條件", "reformist_bonus": -5, "royalist_bonus": 8}'::jsonb,
  '{"name": "分齡規範版", "description": "僅限制童工工時", "reformist_bonus": 5, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 5}'::jsonb),
(4, 2026, '天主教解放法案', '關於天主教徒擔任公職的限制', 'religious',
  '{"name": "完全解放版", "description": "天主教徒可擔任所有公職", "reformist_bonus": 12, "royalist_bonus": -8}'::jsonb,
  '{"name": "維持限制版", "description": "天主教徒不得擔任公職", "reformist_bonus": -8, "royalist_bonus": 12}'::jsonb,
  '{"name": "部分開放版", "description": "開放地方職位但保留中央限制", "reformist_bonus": 5, "royalist_bonus": 3}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": -3}'::jsonb),
(5, 2026, '新聞自由法案', '關於報紙出版與審查制度', 'political',
  '{"name": "完全自由版", "description": "廢除所有出版審查", "reformist_bonus": 12, "royalist_bonus": -10}'::jsonb,
  '{"name": "嚴格審查版", "description": "政府有權審查所有出版物", "reformist_bonus": -10, "royalist_bonus": 12}'::jsonb,
  '{"name": "有限自由版", "description": "廢除事前審查但保留誹謗法", "reformist_bonus": 8, "royalist_bonus": 0}'::jsonb,
  '{"expose_cost_modifier": -3, "alliance_bonus": 0}'::jsonb),
(6, 2026, '濟貧法修正案', '關於救濟貧民的方式與責任', 'social',
  '{"name": "戶外救濟版", "description": "允許在社區內提供救濟", "reformist_bonus": 10, "royalist_bonus": -5}'::jsonb,
  '{"name": "工作院版", "description": "窮人必須進入工作院才能獲得救濟", "reformist_bonus": -8, "royalist_bonus": 10}'::jsonb,
  '{"name": "教區責任版", "description": "由各教區自行決定救濟方式", "reformist_bonus": 3, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 3}'::jsonb),
(7, 2026, '海軍擴張法案', '關於海軍軍費與艦隊規模', 'military',
  '{"name": "大規模擴張版", "description": "建造20艘新戰艦", "reformist_bonus": -5, "royalist_bonus": 12}'::jsonb,
  '{"name": "裁軍版", "description": "削減海軍預算用於民生", "reformist_bonus": 12, "royalist_bonus": -5}'::jsonb,
  '{"name": "維持現狀版", "description": "僅替換老舊艦艇", "reformist_bonus": 3, "royalist_bonus": 5}'::jsonb,
  '{"challenge_damage_modifier": 5, "alliance_bonus": 0}'::jsonb),
(8, 2026, '殖民地自治法案', '關於殖民地的治理模式', 'colonial',
  '{"name": "自治版", "description": "給予殖民地有限自治權", "reformist_bonus": 10, "royalist_bonus": -5}'::jsonb,
  '{"name": "直轄版", "description": "加強倫敦對殖民地的直接控制", "reformist_bonus": -5, "royalist_bonus": 10}'::jsonb,
  '{"name": "代議版", "description": "殖民地可派代表至西敏寺", "reformist_bonus": 8, "royalist_bonus": 0}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 0}'::jsonb),
(9, 2026, '銀行法案', '關於英格蘭銀行的壟斷地位', 'economic',
  '{"name": "自由銀行版", "description": "允許私人設立發鈔銀行", "reformist_bonus": 8, "royalist_bonus": -3}'::jsonb,
  '{"name": "中央壟斷版", "description": "英格蘭銀行獨享發鈔權", "reformist_bonus": -3, "royalist_bonus": 10}'::jsonb,
  '{"name": "雙軌版", "description": "英格蘭銀行主導但允許地方銀行", "reformist_bonus": 5, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 0}'::jsonb),
(10, 2026, '教育法案', '關於國民教育的普及與管理', 'social',
  '{"name": "公立教育版", "description": "政府資助設立公立學校", "reformist_bonus": 12, "royalist_bonus": -5}'::jsonb,
  '{"name": "教會教育版", "description": "教育事務由教會全權管理", "reformist_bonus": -5, "royalist_bonus": 10}'::jsonb,
  '{"name": "混合版", "description": "政府補助教會學校", "reformist_bonus": 5, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": 0, "alliance_bonus": 5}'::jsonb),
(11, 2026, '決鬥禁止法案', '關於禁止上流社會決鬥的法案', 'social',
  '{"name": "全面禁止版", "description": "決鬥等同謀殺", "reformist_bonus": 8, "royalist_bonus": -3}'::jsonb,
  '{"name": "維持傳統版", "description": "決鬥是紳士的權利", "reformist_bonus": -5, "royalist_bonus": 8}'::jsonb,
  '{"name": "規範版", "description": "允許但需報備且有仲裁人", "reformist_bonus": 3, "royalist_bonus": 3}'::jsonb,
  '{"challenge_damage_modifier": 10, "alliance_bonus": -5}'::jsonb),
(12, 2026, '奴隸貿易廢除法案', '關於大英帝國境內奴隸貿易', 'moral',
  '{"name": "即刻廢除版", "description": "立即廢除所有奴隸貿易", "reformist_bonus": 15, "royalist_bonus": -8}'::jsonb,
  '{"name": "漸進廢除版", "description": "十年過渡期逐步廢除", "reformist_bonus": 5, "royalist_bonus": 3}'::jsonb,
  '{"name": "補償版", "description": "廢除但補償奴隸主", "reformist_bonus": 8, "royalist_bonus": 5}'::jsonb,
  '{"expose_cost_modifier": -5, "alliance_bonus": 5}'::jsonb);
